export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export const GET_WEATHER_DATA_FAILURE = 'GET_WEATHER_DATA_FAILURE';
export const GET_WEATHER_DATA_REQUEST = 'GET_WEATHER_DATA_REQUEST';
export const GET_LOCATION_DATA = 'GET_LOCATION_DATA';
export const GET_LOCATION_DATA_SUCCESS = 'GET_LOCATION_DATA_SUCCESS';
export const GET_LOCATION_DATA_FAILURE = 'GET_LOCATION_DATA_FAILURE';
export const GET_LOCATION_DATA_REQUEST = 'GET_LOCATION_DATA_REQUEST';
